[tool.poetry]
name = "zettelkasten-cli"
version = "0.2.0"
description = "CLI to merge Vim and Obsidian Zettelkasten"
authors = ["Mischa van den Burg"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
typer = {extras = ["all"], version = "^0.12.3"}
wget = "^3.2"

[tool.poetry.scripts]
zk = "zettelkasten_cli.main:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

